flow:
  id: manage-rules
  name: Manage Rules
  type: traditional
  domain: settings
  description: Create or update automation rules with conditions and actions

trigger:
  id: trigger-pQ2nT6eH
  type: trigger
  position: { x: 400, y: 50 }
  connections:
    - targetNodeId: input-qR3oU7fJ
  spec:
    event: "HTTP POST /api/v1/settings/rules"
    source: API Gateway
    description: Create or update a rule endpoint
  label: Manage Rules Request

nodes:
  - id: input-qR3oU7fJ
    type: input
    position: { x: 400, y: 180 }
    connections:
      - targetNodeId: data_store-rS4pV8gK
        sourceHandle: valid
      - targetNodeId: terminal-uV7sY1jN
        sourceHandle: invalid
    spec:
      fields:
        - name: name
          type: string
          required: true
        - name: conditions
          type: json
          required: true
        - name: actions
          type: json
          required: true
      validation: "name must be non-empty string (max 200), conditions must be valid JSON object, actions must be valid JSON object"
      description: Validate rule creation payload
    label: Validate Input

  - id: terminal-uV7sY1jN
    type: terminal
    position: { x: 650, y: 180 }
    connections: []
    spec:
      outcome: error
      status: 422
      body:
        error: "VALIDATION_ERROR"
        message: "$.validation_errors"
      description: Invalid rule data
    label: Invalid Input

  - id: data_store-rS4pV8gK
    type: data_store
    position: { x: 400, y: 310 }
    connections:
      - targetNodeId: event-sT5qW9hL
        sourceHandle: success
      - targetNodeId: terminal-vW8tZ2kP
        sourceHandle: error
    spec:
      operation: upsert
      model: Rule
      upsert_key: ["name"]
      data:
        name: "$.name"
        conditions: "$.conditions"
        actions: "$.actions"
        is_active: true
      description: Create or update rule by unique name
    label: Upsert Rule

  - id: terminal-vW8tZ2kP
    type: terminal
    position: { x: 650, y: 310 }
    connections: []
    spec:
      outcome: error
      status: 500
      body:
        error: "INTERNAL_ERROR"
        message: "Failed to save rule"
      description: Database error saving rule
    label: DB Error (Upsert)

  - id: event-sT5qW9hL
    type: event
    position: { x: 400, y: 440 }
    connections:
      - targetNodeId: terminal-tU6rX1iM
    spec:
      direction: emit
      event_name: RulesUpdated
      payload:
        rule_name: "$.name"
        operation: "$.upsert_operation"
      async: true
      description: Notify downstream that rules have been updated
    label: Emit RulesUpdated

  - id: terminal-tU6rX1iM
    type: terminal
    position: { x: 400, y: 570 }
    connections: []
    spec:
      outcome: success
      status: 200
      body:
        message: "Rule saved"
        rule_name: "$.name"
      description: Rule created or updated successfully
    label: Success 200

metadata:
  created: "2026-02-21T00:00:00Z"
  modified: "2026-02-21T00:00:00Z"
