flow:
  id: user-register
  name: User Registration
  type: traditional
  domain: users
  description: Register a new user account
trigger:
  id: trigger-K7mR9xV2
  type: trigger
  position:
    x: 400
    y: 50
  connections:
    - targetNodeId: input-F3nL8qW5
  spec:
    event: HTTP POST /api/users/register
    source: API Gateway
    description: Registration request received
  label: API Request
nodes:
  - id: input-F3nL8qW5
    type: input
    position:
      x: 400
      y: 200
    connections:
      - targetNodeId: decision-P2xJ6sT4
        sourceHandle: valid
      - targetNodeId: terminal-invalid
        sourceHandle: invalid
    spec:
      fields:
        - name: email
          type: string
          required: true
        - name: password
          type: string
          required: true
        - name: name
          type: string
          required: true
      validation: Email format, password min 8 chars, name required
      description: Registration form data
    label: Validate Input
  - id: decision-P2xJ6sT4
    type: decision
    position:
      x: 260
      y: 350
    connections:
      - targetNodeId: process-Y8hD3bK9
        sourceHandle: "true"
      - targetNodeId: terminal-duplicate
        sourceHandle: "false"
    spec:
      condition: email_available
      trueLabel: Available
      falseLabel: Already taken
      description: Check if email already registered
    label: Email Available?
  - id: process-Y8hD3bK9
    type: process
    position:
      x: 260
      y: 500
    connections:
      - targetNodeId: event-U5cW1zM7
    spec:
      action: Hash password and create user record
      service: UserService.register
      description: Create user in database
    label: Create User
  - id: event-U5cW1zM7
    type: event
    position:
      x: 400
      y: 650
    connections:
      - targetNodeId: terminal-success
    spec:
      event_name: UserRegistered
      schema: User
      description: Emit user registered event
      direction: emit
    label: Emit UserRegistered
  - id: terminal-success
    type: terminal
    position:
      x: 400
      y: 800
    connections: []
    spec:
      outcome: success
      description: Return created user with JWT token
      status: 201
      body:
        message: User registered successfully
        user: $.user
        token: $.jwt_token
    label: Success
  - id: terminal-duplicate
    type: terminal
    position:
      x: 540
      y: 500
    connections: []
    spec:
      outcome: error
      description: Return 409 Conflict
      status: 409
      body:
        error: DUPLICATE_ENTRY
        message: Email already registered
    label: Duplicate Email
  - id: terminal-invalid
    type: terminal
    position:
      x: 540
      y: 350
    connections: []
    spec:
      outcome: error
      description: Return 422 Validation Error
      status: 422
      body:
        error: VALIDATION_ERROR
        message: $.validation_errors
    label: Invalid Input
metadata:
  created: 2025-02-19T00:00:00Z
  modified: 2026-02-19T20:14:55.451Z
